arcoiris=("azul","verde","rojo","amarillo","morado")
print(arcoiris)
print("--longitud arcoiris--")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print("Elementos de la tupla")
print(animales[2])
rateros = ("roberto", "emi", "david")
y = list(rateros)
y[0] = "adriel"
x = tuple(y)
print(x)
print("Agregando elementos")
Nanimal=("boby","chetos")
y = list(Nanimal)
print(y)
y.append("tontolin")
otratupla = tuple(y)

print(otratupla)
print("Uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)